-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dwh.dim_city
(
    city_id serial NOT NULL,
    city_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    region_id integer NOT NULL,
    CONSTRAINT dim_city_pkey PRIMARY KEY (city_id),
    CONSTRAINT dim_city_city_name_region_id_key UNIQUE (city_name, region_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_company
(
    company_id serial NOT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    inn character varying(12) COLLATE pg_catalog."default",
    city_id integer,
    industry_id integer,
    is_verified boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT dim_company_pkey PRIMARY KEY (company_id),
    CONSTRAINT dim_company_inn_key UNIQUE (inn)
);

CREATE TABLE IF NOT EXISTS dwh.dim_education_level
(
    level_id serial NOT NULL,
    level_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_education_level_pkey PRIMARY KEY (level_id),
    CONSTRAINT dim_education_level_level_name_key UNIQUE (level_name)
);

CREATE TABLE IF NOT EXISTS dwh.dim_industry
(
    industry_id serial NOT NULL,
    industry_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    okved_code character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT dim_industry_pkey PRIMARY KEY (industry_id),
    CONSTRAINT dim_industry_industry_name_key UNIQUE (industry_name)
);

CREATE TABLE IF NOT EXISTS dwh.dim_program
(
    program_id serial NOT NULL,
    program_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    program_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level_id integer,
    CONSTRAINT dim_program_pkey PRIMARY KEY (program_id),
    CONSTRAINT dim_program_program_code_key UNIQUE (program_code)
);

CREATE TABLE IF NOT EXISTS dwh.dim_region
(
    region_id serial NOT NULL,
    region_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_region_pkey PRIMARY KEY (region_id),
    CONSTRAINT dim_region_region_name_key UNIQUE (region_name)
);

CREATE TABLE IF NOT EXISTS dwh.dim_specialization_education
(
    spec_edu_id serial NOT NULL,
    spec_edu_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    spec_edu_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    program_id integer NOT NULL,
    CONSTRAINT dim_specialization_education_pkey PRIMARY KEY (spec_edu_id),
    CONSTRAINT dim_specialization_education_spec_edu_code_key UNIQUE (spec_edu_code)
);

CREATE TABLE IF NOT EXISTS dwh.dim_specialization_work
(
    spec_work_id serial NOT NULL,
    spec_work_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    spec_work_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_specialization_work_pkey PRIMARY KEY (spec_work_id),
    CONSTRAINT dim_specialization_work_spec_work_code_key UNIQUE (spec_work_code)
);

CREATE TABLE IF NOT EXISTS dwh.dim_student
(
    student_hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    birth_year integer,
    gender character(1) COLLATE pg_catalog."default",
    graduation_year integer NOT NULL,
    university_id integer,
    spec_edu_id integer,
    CONSTRAINT dim_student_pkey PRIMARY KEY (student_hash)
);

CREATE TABLE IF NOT EXISTS dwh.dim_university
(
    university_id serial NOT NULL,
    university_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    university_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city_id integer NOT NULL,
    foundation_year integer,
    rating numeric(5, 2),
    website character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT dim_university_pkey PRIMARY KEY (university_id),
    CONSTRAINT dim_university_university_code_key UNIQUE (university_code)
);

CREATE TABLE IF NOT EXISTS dwh.fact_employment
(
    employment_id serial NOT NULL,
    student_hash character varying(64) COLLATE pg_catalog."default",
    company_id integer,
    spec_work_id integer,
    salary numeric(10, 2),
    "position" character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    is_employed boolean DEFAULT true,
    works_by_specialty boolean,
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT fact_employment_pkey PRIMARY KEY (employment_id)
);

CREATE TABLE IF NOT EXISTS mart.aggregated_by_year
(
    graduation_year integer,
    total_graduates bigint,
    avg_salary numeric,
    employment_rate numeric
);

CREATE TABLE IF NOT EXISTS mart.employment_fact_flat
(
    student_hash character varying(64) COLLATE pg_catalog."default",
    birth_year integer,
    gender character(1) COLLATE pg_catalog."default",
    graduation_year integer,
    company_name character varying(255) COLLATE pg_catalog."default",
    salary numeric(10, 2),
    "position" character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    is_employed boolean,
    works_by_specialty boolean
);

CREATE TABLE IF NOT EXISTS mart.mart_employment_flat
(
    student_hash character varying(64) COLLATE pg_catalog."default",
    birth_year integer,
    gender character(1) COLLATE pg_catalog."default",
    graduation_year integer,
    university_name character varying(255) COLLATE pg_catalog."default",
    university_rating numeric(5, 2),
    university_city character varying(100) COLLATE pg_catalog."default",
    region_name character varying(100) COLLATE pg_catalog."default",
    program_code character varying(20) COLLATE pg_catalog."default",
    program_name character varying(255) COLLATE pg_catalog."default",
    education_level character varying(50) COLLATE pg_catalog."default",
    spec_edu_code character varying(20) COLLATE pg_catalog."default",
    specialization_education character varying(255) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    industry_name character varying(100) COLLATE pg_catalog."default",
    spec_work_code character varying(20) COLLATE pg_catalog."default",
    specialization_work character varying(255) COLLATE pg_catalog."default",
    salary numeric(10, 2),
    "position" character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    is_employed boolean,
    works_by_specialty boolean,
    etl_updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS mart.mart_program_aggregated
(
    program_code character varying(20) COLLATE pg_catalog."default",
    program_name character varying(255) COLLATE pg_catalog."default",
    total_graduates bigint,
    avg_salary numeric,
    employment_rate numeric
);

CREATE TABLE IF NOT EXISTS public.articles
(
    id serial NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    excerpt text COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    image_url text COLLATE pg_catalog."default",
    CONSTRAINT articles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS staging.stg_graduates
(
    id serial NOT NULL,
    local_student_id character varying(50) COLLATE pg_catalog."default",
    university_code character varying(20) COLLATE pg_catalog."default",
    program_code character varying(20) COLLATE pg_catalog."default",
    program_name character varying(255) COLLATE pg_catalog."default",
    specialization_edu_code character varying(20) COLLATE pg_catalog."default",
    specialization_edu_name character varying(255) COLLATE pg_catalog."default",
    birth_year integer,
    graduation_year integer,
    gender character(1) COLLATE pg_catalog."default",
    is_employed boolean,
    company_name character varying(255) COLLATE pg_catalog."default",
    inn character varying(12) COLLATE pg_catalog."default",
    industry_name character varying(100) COLLATE pg_catalog."default",
    "position" character varying(255) COLLATE pg_catalog."default",
    salary numeric(10, 2),
    specialization_work_code character varying(20) COLLATE pg_catalog."default",
    specialization_work_name character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    works_by_specialty boolean,
    load_timestamp timestamp without time zone DEFAULT timezone('utc'::text, now()),
    task_id character varying(50) COLLATE pg_catalog."default",
    student_hash character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT stg_graduates_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS dwh.dim_city
    ADD CONSTRAINT dim_city_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES dwh.dim_region (region_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_company
    ADD CONSTRAINT dim_company_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES dwh.dim_city (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_company
    ADD CONSTRAINT dim_company_industry_id_fkey FOREIGN KEY (industry_id)
    REFERENCES dwh.dim_industry (industry_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_program
    ADD CONSTRAINT dim_program_level_id_fkey FOREIGN KEY (level_id)
    REFERENCES dwh.dim_education_level (level_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_specialization_education
    ADD CONSTRAINT dim_specialization_education_program_id_fkey FOREIGN KEY (program_id)
    REFERENCES dwh.dim_program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_student
    ADD CONSTRAINT dim_student_spec_edu_id_fkey FOREIGN KEY (spec_edu_id)
    REFERENCES dwh.dim_specialization_education (spec_edu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_student
    ADD CONSTRAINT dim_student_university_id_fkey FOREIGN KEY (university_id)
    REFERENCES dwh.dim_university (university_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_university
    ADD CONSTRAINT dim_university_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES dwh.dim_city (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_employment
    ADD CONSTRAINT fact_employment_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES dwh.dim_company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_employment
    ADD CONSTRAINT fact_employment_spec_work_id_fkey FOREIGN KEY (spec_work_id)
    REFERENCES dwh.dim_specialization_work (spec_work_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_employment
    ADD CONSTRAINT fact_employment_student_hash_fkey FOREIGN KEY (student_hash)
    REFERENCES dwh.dim_student (student_hash) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;